drop table if exists sys_user;
drop table if exists sys_organization;
drop table if exists sys_resource;
drop table if exists sys_role;

drop table if exists sys_user;
drop table if exists sys_project;
drop table if exists sys_user_project;
drop table if exists sys_project_user_group;
drop table if exists sys_role;
drop table if exists sys_role_extend;
drop table if exists sys_role_group;
drop table if exists sys_user_project_role;
drop table if exists sys_project_user_group_role;
drop table if exists sys_permit;
drop table if exists sys_role_permit;
drop table if exists sys_menu_resource;
drop table if exists sys_element_resource;
drop table if exists sys_url_resource;

create table sys_user (
  user_id bigint generated by default as identity,
  username varchar(100),
  password varchar(100),
  salt varchar(100),
  locked bool default false,
  owner_id bigint,
  primary key (user_id)
);
create table sys_project (
  project_id bigint generated by default as identity,
  project_name varchar(100),
  project_key varchar(100),
  project_secret varchar(100),
  project_desc varchar(200),
  owner_id bigint,
  primary key (project_id)
);
create table sys_user_project (
  user_project_id bigint generated by default as identity,
  user_id bigint,
  project_id bigint,
  user_project_type varchar(100),
  project_user_group_id bigint,
  primary key (user_project_id)
);
create table sys_project_user_group (
  project_user_group_id bigint generated by default as identity,
  project_id bigint,
  user_project_group_name varchar(100),
  parent_id bigint,
  user_project_group_desc varchar(200),
  primary key (project_user_group_id)
);
create table sys_role (
  role_id bigint generated by default as identity,
  role_name varchar(100),
  role_group_id bigint,
  available bool default true,
  role_type varchar(100),
  role_desc varchar(200),
  primary key (role_id)
);
create table sys_role_extend (
  role_extend_id bigint generated by default as identity,
  role_id bigint,
  parent_id bigint,
  primary key (role_extend_id)
);
create table sys_role_group (
  role_group_id bigint generated by default as identity,
  role_group_name varchar(100),
  parent_id bigint,
  role_group_desc varchar(200),
  primary key (role_group_id)
);
create table sys_user_project_role (
  user_project_role_id bigint generated by default as identity,
  user_project_id bigint,
  role_id bigint,
  primary key (user_project_role_id)
);
create table sys_project_user_group_role (
  project_user_group_role_id bigint generated by default as identity,
  project_user_group_id bigint,
  role_id bigint,
  primary key (project_user_group_role_id)
);

create table sys_permit (
  permit_id bigint generated by default as identity,
  permit_name varchar(100),
  permit_type varchar(100),
  parent_id bigint,
  primary key (permit_id)
);
create table sys_role_permit (
  role_permit_id bigint generated by default as identity,
  role_id bigint,
  permit_id bigint,
  primary key (role_permit_id)
);
create table sys_menu_resource (
  menu_resource_id bigint generated by default as identity,
  menu_resource_name varchar(100),
  menu_resource_url varchar(200),
  permit_id bigint,
  primary key (menu_resource_id)
);
create table sys_element_resource (
  element_resource_id bigint generated by default as identity,
  element_resource_name varchar(100),
  element_resource_code varchar(100),
  permit_id bigint,
  primary key (element_resource_id)
);
create table sys_url_resource (
  url_resource_id bigint generated by default as identity,
  url_resource_name varchar(100),
  url_path varchar(200),
  permit_id bigint,
  primary key (url_resource_id)
);